### ISSUE TITLE
Example of dicomsorter with --filename-format

### ISSUE THREAD

**Issue by solmosg** [dicomsort/dicomsorter#6]
Hello,
First of all thank you for both tools, dicomsorter and dicomsort!  They are really  usefull. 

I could run dicomsort (GUI) in order to split a dicom folder according to several DICOM tags, such as 'StudyDate', 'ViewName'.  Unluckily I could not do a similar thing with command line dicomsorter. I guess I am using a proper specification of --filename-format FILENAME option.

I would like to split my dicom folder in a tree with this hierarchy: PatientID / StudyDate / ViewName / Image_instances:

dicomsorter --file-format '%(PatientID)s - %(StudyDate)s %(ViewName)s '  ~/source  ~/destination

I tried multiple things, changing order, without sucess. Any help?

Thank you very much

**Comment by suever** [comment]
Thanks for using the tools! I'm glad you find them useful!

This project is still a Work in Progress, but I think it should still be able to do exactly what you need it to do. 

In order to specify the directory hierarchy, you will want to use the `--path` option to provide the fields that should be used for generating the hierarchy. The `--filename-format` is specifically for the name of the resulting file (not the directory in which it is placed). 

For your example, you may want to try something like the following:

```
dicomsorter --filename-format "%(PatientID)s - %(StudyDate)s %(ViewName)s" --path PatientId StudyDate ViewName ~/source ~/destination
```

If that does not work, do you mind sharing the errors (if any) or the unexpected output that it yields?

Thanks!

**Comment by solmosg** [comment]
Sorry, I tried several options without success.
I got the following error message using your proposal:

dicomsorter: error: the following arguments are required: input_directory, output_directory

Thanks for helping!

**Comment by suever** [comment]
> Sorry, I tried several options without success.
> I got the following error message using your proposal:
> 
> dicomsorter: error: the following arguments are required: input_directory, output_directory
> 
> Thanks for helping!

Oh yea I've encountered this before. This is a strange quirk of the `argparse` library that I need to see if there is a way around it. Since we use the `--path` flag and provide multiple values, it thinks that the input and output directory at the end are part of this parameter rather than the input and output directory. The short-term fix until I get this figured out is to put them *before* the `--path` arg

```
dicomsorter ~/source ~/destination --filename-format "%(PatientID)s - %(StudyDate)s %(ViewName)s" --path PatientId StudyDate ViewName 
```

Does that help?

**Comment by solmosg** [comment]
Great! It worked! 

One more question. When using dicomsort (GUI) it seems that there should be always 'SeriesDescription' field. I would like to keep a similar option for command line dicomsorter. Which option should I use?

In addition, when using dicomsort (GUI) on a DICOM study where some series do not have one the DICOM fields used for path option (such as ViewName'), the corresponding files are assigned to 'UNKNOWN' folder with its corresponding 'Series000x', which is a nice decision. How to obtain a similar result using command line dicomsorter? Which option? Just post-processing and renaming files? 

Thank you very much
Salvador

**Comment by suever** [comment]
There is no way to always have the CLI use the `SeriesDescription`. You can, however, provide it using the `--path` argument as `--path SeriesDescription` and that will use the ["enhanced" description](https://github.com/dicomsort/dicomsorter/blob/master/dicomsorter/dicom_utils.py#L123). The intent of the CLI is to be more explicit and less implicit.

As far as your second point, what does the current version result in in that case? I can't say that I've tested that! Let me know and we can work from there

**Comment by solmosg** [comment]
Everything is ok, Thanks a lot!
